---
title: "data_wrangling_i"
output: github_document
---

Practice on Data Import!

```{r}
library(tidyverse)
```

Path

```{r}
getwd()
```

Importing data tables.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
pups_data = read_csv(file = "./data/FAS_pups.csv")
```

```{r}
names(litters_data)
litters_data = janitor::clean_names(litters_data)
names(litters_data)
names(pups_data)
pups_data = janitor::clean_names(pups_data)
names(pups_data)
```

```{r}
litters_data
tail(litters_data, 5)
```

```{r}
skimr::skim(litters_data)
```

Arguments to read_*.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv", skip = 10, col_names = FALSE)
head(litters_data)
pups_data = read_csv(file = "./data/FAS_pups.csv", skip = 10, col_names = FALSE)
head(pups_data)
```

Parsing columns.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
 col_types = cols(
   Group = col_character(), 
   `Litter Number` = col_character(),
   `GD0 weight` = col_double(),
   `GD18 weight` = col_double(),
   `GD of Birth` = col_integer(),
   `Pups born alive` = col_integer(),
   `Pups dead @ birth` = col_integer(),
   `Pups survive` = col_integer()
   ))
tail(litters_data)
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = "ccddiiii"
)
pups_data = read_csv(file = "./data/FAS_pups.csv",
 col_types = cols(
   `Litter Number` = col_character(),
   `Sex` = col_integer(),
   `PD ears` = col_integer(),
   `PD eyes` = col_integer(),
   `PD pivot` = col_integer(),
   `PD walk` = col_integer()
   ))
tail(pups_data)
read_csv(file = "./data/FAS_pups.csv",
  col_types = "ciiiii")
```

Other file formats.

```{r}
library(readxl)
mlb11_data = read_excel("data/mlb11.xlsx", n_max = 20)
head(mlb11_data,5)
```

```{r}
library(haven)
pulse_data = read_sas("./data/public_pulse_data.sas7bdat")
head(pulse_data,5)
```

Comparison with Base R

```{r}
base_pups_data = read.csv(file = "./data/FAS_pups.csv")
base_pups_data = janitor::clean_names(base_pups_data)
names(base_pups_data)
```

